apiVersion: v1
kind: Service

metadata:
  name: {{ include "app.service.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}

spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "common.app-labels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
