version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - hello-server-1
      - hello-server-2

  hello-server-1:
    build: .

  hello-server-2:
    build: .
