version: "3.9"

services:
  load-balancer:
    image: nginx:1.27.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - hello-server-1
      - hello-server-2

  hello-server-1:
    build: .

  hello-server-2:
    build: .
