services:
  reverse-proxy:
    image: nginx:1.27.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - hello-server

  hello-server:
    build: .
    image: hello-server:0.7
    deploy:
      replicas: 2
