services:
  reverse-proxy:
    image: nginx:1.27.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-compose.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      hello-server:
        condition: service_started

  hello-server:
    # build: . uncomment if image rebuild needed
    image: tanvirrashiddon/hello-server:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 2
