services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      # HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  hello-server:
    build: .
    image: hello-server:0.7
    deploy:
      replicas: 2
    labels:
      - "traefik.http.routers.hello-server.rule=Host(`localhost`)"
