services:
  reverse-proxy:
    image: traefik:v3.3
    restart: always
    command:
      - "--configFile=./traefik/traefik.yml" # /etc/traefik/traefik.yml
    ports:
      # HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      # use dynamic configuration if needed
      # - "./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"

  hello-server:
    build: .
    image: tanvirrashiddon/hello-server:latest
    restart: always
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-server.rule=Host(`localhost`)"
      - "traefik.http.routers.hello-server.entrypoints=web"
      - "traefik.http.routers.hello-server.middlewares=test-ratelimit"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=20"
