apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-{{ .Values.rp.name }}-service
  labels:
    {{- include "common.labels" . | nindent 4 }}

spec:
  type: {{ .Values.rp.service.type }}
  selector:
    {{- include "common.rp-labels" . | nindent 6 }}
  ports:
    - name: http
      nodePort: {{ .Values.rp.service.ports.http.nodePort }}
      port: {{ .Values.rp.service.ports.http.port }}
      protocol: {{ .Values.rp.service.ports.http.protocol }}
    - name: https
      nodePort: {{ .Values.rp.service.ports.https.nodePort }}
      port: {{ .Values.rp.service.ports.https.port }}
      protocol: {{ .Values.rp.service.ports.https.protocol }}
