apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-{{ .Values.rp.name }}-deploy
  labels:
    {{- include "common.labels" . | nindent 4 }}

spec:
  replicas: {{ default 1 .Values.rp.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "common.rp-labels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Values.rp.name }}-pod
      labels:
        {{- include "common.rp-labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ include "rp.config.volume" . }}
          configMap:
            name: {{ include "rp.configmap.name" . }}
        - name: {{ include "rp.secret.volume" . }}
          secret:
            secretName: {{ include "rp.secret.name" . }}
      containers:
        - name: {{ .Values.rp.name }}-container
          image: {{ .Values.rp.deploy.image.repository }}:{{ default "latest" .Values.rp.deploy.image.tag }}
          ports:
            - containerPort: {{ .Values.rp.deploy.image.ports.http }}
            - containerPort: {{ .Values.rp.deploy.image.ports.https }}
          imagePullPolicy: {{ .Values.rp.deploy.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "rp.config.volume" . }}
              mountPath: {{ .Values.rp.deploy.image.mounts.configPath }}
              readOnly: true
            - name: {{ include "rp.secret.volume" . }}
              mountPath: {{ .Values.rp.deploy.image.mounts.secretPath }}
              readOnly: true
