apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "rp.configmap.name" . }}
  namespace: {{ .Release.namespace }}

data:
  default.conf: |
    upstream application-server {
      server {{ include "app.service.name" . }}:{{ .Values.rp.deploy.image.ports.http }};
    }

    server {
      listen       {{ .Values.rp.deploy.image.ports.http }} default_server;
      listen  [::]:{{ .Values.rp.deploy.image.ports.http }} default_server ipv6only=on;

      listen {{ .Values.rp.deploy.image.ports.https }} ssl;

      root /usr/share/nginx/html;
      index index.html;

      server_name localhost;
      ssl_certificate {{ .Values.rp.deploy.image.mounts.secretPath }}/tls.crt;
      ssl_certificate_key {{ .Values.rp.deploy.image.mounts.secretPath }}/tls.key;

      location / {
        proxy_pass http://application-server/;

        proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
