apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deploy
  labels:
    app: hello-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-pod
      app: hello-app
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-pod
        app: hello-app
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-secret-volume
          secret:
            secretName: nginx-secret
      containers:
        - name: nginx-container
          image: nginx:1.27.3
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx-k8s.conf
              readOnly: true
            - name: nginx-secret-volume
              mountPath: /etc/nginx/ssl
