apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  labels:
    app: hello-app

spec:
  type: NodePort
  selector:
    name: nginx-pod
    app: hello-app
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 80
