app:
  name: hello-server
  deploy:
    replicas: 2
    image:
      repository: localhost:5000/hello-server
      tag: ""
      pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    protocol: TCP
    targetPort: 80

rp:
  name: nginx
  deploy:
    replicas: 1
    image:
      repository: nginx
      tag: 1.27.3
      pullPolicy: IfNotPresent
      ports:
        http: 80
        https: 443
      mounts:
        configPath: /etc/nginx/conf.d
        secretPath: /etc/nginx/ssl
  service:
    type: NodePort
    ports:
      http:
        nodePort: 30080
        port: 80
        protocol: TCP
      https:
        nodePort: 30443
        port: 443
        protocol: TCP
