apiVersion: v1
kind: Service

metadata:
  name: hello-server-service
  labels:
    app: hello-app

spec:
  type: ClusterIP
  selector:
    name: hello-server-pod
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
