apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  labels:
    app: hello-app

spec:
  type: NodePort
  selector:
    name: nginx-pod
    app: hello-app
  ports:
    - name: http
      nodePort: 30080
      port: 80
      protocol: TCP
    - name: https
      nodePort: 30443
      port: 443
      protocol: TCP
