apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-server-deploy
  labels:
    name: hello-server-deploy
    app: hello-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-server-pod
      app: hello-app
  template:
    metadata:
      labels:
        name: hello-server-pod
        app: hello-app
    spec:
      containers:
        - name: hello-server-container
          image: localhost:5000/hello-server:latest
